// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import "github.com/dmitrymomot/mailer/template/components"
import "github.com/dmitrymomot/mailer/template/utils"
import "braces.dev/errtrace"

func ComponentsPreview() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			templ_7745c5c3_Var3 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
				if !templ_7745c5c3_IsBuffer {
					templ_7745c5c3_Buffer = templ.GetBuffer()
					defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
				}
				templ_7745c5c3_Err = components.Logo("/assets/logo.svg", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return errtrace.Wrap(templ_7745c5c3_Err)
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
				if templ_7745c5c3_Err != nil {
					return errtrace.Wrap(templ_7745c5c3_Err)
				}
				if !templ_7745c5c3_IsBuffer {
					_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
				}
				return errtrace.Wrap(templ_7745c5c3_Err)
			})
			templ_7745c5c3_Err = components.Wrapper().Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			templ_7745c5c3_Var4 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
				if !templ_7745c5c3_IsBuffer {
					templ_7745c5c3_Buffer = templ.GetBuffer()
					defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
				}
				templ_7745c5c3_Var5 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
					if !templ_7745c5c3_IsBuffer {
						templ_7745c5c3_Buffer = templ.GetBuffer()
						defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
					}
					templ_7745c5c3_Var6 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
						if !templ_7745c5c3_IsBuffer {
							templ_7745c5c3_Buffer = templ.GetBuffer()
							defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
						}
						templ_7745c5c3_Var7 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
							templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
							if !templ_7745c5c3_IsBuffer {
								templ_7745c5c3_Buffer = templ.GetBuffer()
								defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
							}
							templ_7745c5c3_Err = components.H1("Hello, World!").Render(ctx, templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var8 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Lorem ipsum dolor sit amet, consectetur ")
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								templ_7745c5c3_Err = components.LabelFilled(utils.Primary, "test label").Render(ctx, templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui. Nullam vel erat sed elit viverra aliquet. Aenean auctor wisi et urna. Aliquam erat volutpat. Duis ac turpis. Integer rutrum ante eu lacus. Link example: ")
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								templ_7745c5c3_Err = components.Link("Example", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.P().Render(templ.WithChildren(ctx, templ_7745c5c3_Var8), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							if !templ_7745c5c3_IsBuffer {
								_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
							}
							return errtrace.Wrap(templ_7745c5c3_Err)
						})
						templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var7), templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return errtrace.Wrap(templ_7745c5c3_Err)
						}
						if !templ_7745c5c3_IsBuffer {
							_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
						}
						return errtrace.Wrap(templ_7745c5c3_Err)
					})
					templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var6), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					templ_7745c5c3_Err = components.Divider().Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					templ_7745c5c3_Var9 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
						if !templ_7745c5c3_IsBuffer {
							templ_7745c5c3_Buffer = templ.GetBuffer()
							defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
						}
						templ_7745c5c3_Var10 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
							templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
							if !templ_7745c5c3_IsBuffer {
								templ_7745c5c3_Buffer = templ.GetBuffer()
								defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
							}
							templ_7745c5c3_Err = components.H2("Subheading h2").Render(ctx, templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var11 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Aliqua excepteur duis do exercitation. Dolor velit commodo aliqua ipsum id aute qui sit amet ullamco in incididunt.")
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.P().Render(templ.WithChildren(ctx, templ_7745c5c3_Var11), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							if !templ_7745c5c3_IsBuffer {
								_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
							}
							return errtrace.Wrap(templ_7745c5c3_Err)
						})
						templ_7745c5c3_Err = components.ColHalf(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var10), templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return errtrace.Wrap(templ_7745c5c3_Err)
						}
						_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
						if templ_7745c5c3_Err != nil {
							return errtrace.Wrap(templ_7745c5c3_Err)
						}
						templ_7745c5c3_Var12 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
							templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
							if !templ_7745c5c3_IsBuffer {
								templ_7745c5c3_Buffer = templ.GetBuffer()
								defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
							}
							templ_7745c5c3_Err = components.H2("Subheading h2").Render(ctx, templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var13 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Sit est ex dolor dolore veniam fugiat ea ad elit Lorem quis.")
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.P().Render(templ.WithChildren(ctx, templ_7745c5c3_Var13), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							if !templ_7745c5c3_IsBuffer {
								_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
							}
							return errtrace.Wrap(templ_7745c5c3_Err)
						})
						templ_7745c5c3_Err = components.ColHalf(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var12), templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return errtrace.Wrap(templ_7745c5c3_Err)
						}
						if !templ_7745c5c3_IsBuffer {
							_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
						}
						return errtrace.Wrap(templ_7745c5c3_Err)
					})
					templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var9), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					templ_7745c5c3_Var14 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
						if !templ_7745c5c3_IsBuffer {
							templ_7745c5c3_Buffer = templ.GetBuffer()
							defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
						}
						templ_7745c5c3_Var15 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
							templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
							if !templ_7745c5c3_IsBuffer {
								templ_7745c5c3_Buffer = templ.GetBuffer()
								defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
							}
							templ_7745c5c3_Err = components.H2("List example").Render(ctx, templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var16 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Nisi incididunt qui reprehenderit sit excepteur elit.")
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.P().Render(templ.WithChildren(ctx, templ_7745c5c3_Var16), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Err = components.List(
								"Velit occaecat enim enim eu mollit exercitation.",
								"Exercitation adipisicing incididunt nisi ipsum tempor non culpa amet minim aliquip aliquip.",
								"Eu labore aliquip aliquip laboris.",
								"Eu irure in esse irure laboris esse irure.",
								"Minim nostrud dolor amet fugiat ullamco reprehenderit.",
							).Render(ctx, templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							if !templ_7745c5c3_IsBuffer {
								_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
							}
							return errtrace.Wrap(templ_7745c5c3_Err)
						})
						templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var15), templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return errtrace.Wrap(templ_7745c5c3_Err)
						}
						if !templ_7745c5c3_IsBuffer {
							_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
						}
						return errtrace.Wrap(templ_7745c5c3_Err)
					})
					templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var14), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					templ_7745c5c3_Err = components.Divider().Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					templ_7745c5c3_Var17 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
						if !templ_7745c5c3_IsBuffer {
							templ_7745c5c3_Buffer = templ.GetBuffer()
							defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
						}
						templ_7745c5c3_Var18 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
							templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
							if !templ_7745c5c3_IsBuffer {
								templ_7745c5c3_Buffer = templ.GetBuffer()
								defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
							}
							templ_7745c5c3_Var19 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var20 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Filled button examples.")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.P().Render(templ.WithChildren(ctx, templ_7745c5c3_Var20), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var19), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var21 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var22 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									templ_7745c5c3_Err = components.ButtonFilled(utils.AlignLeft, utils.Primary, "Button Primary", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var22), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var21), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var23 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var24 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									templ_7745c5c3_Err = components.ButtonFilled(utils.AlignLeft, utils.Secondary, "Button Secondary", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var24), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var23), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var25 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var26 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									templ_7745c5c3_Err = components.ButtonFilled(utils.AlignLeft, utils.Success, "Button Success", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var26), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var25), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var27 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var28 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									templ_7745c5c3_Err = components.ButtonFilled(utils.AlignLeft, utils.Info, "Button Info", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var28), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var27), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var29 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var30 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									templ_7745c5c3_Err = components.ButtonFilled(utils.AlignLeft, utils.Danger, "Button Danger", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var30), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var29), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var31 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var32 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									templ_7745c5c3_Err = components.ButtonFilled(utils.AlignLeft, utils.Warning, "Button Warning", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var32), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var31), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							if !templ_7745c5c3_IsBuffer {
								_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
							}
							return errtrace.Wrap(templ_7745c5c3_Err)
						})
						templ_7745c5c3_Err = components.ColHalf(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var18), templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return errtrace.Wrap(templ_7745c5c3_Err)
						}
						_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
						if templ_7745c5c3_Err != nil {
							return errtrace.Wrap(templ_7745c5c3_Err)
						}
						templ_7745c5c3_Var33 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
							templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
							if !templ_7745c5c3_IsBuffer {
								templ_7745c5c3_Buffer = templ.GetBuffer()
								defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
							}
							templ_7745c5c3_Var34 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var35 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Outlined button examples.")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.P().Render(templ.WithChildren(ctx, templ_7745c5c3_Var35), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var34), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var36 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var37 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									templ_7745c5c3_Err = components.ButtonOutlined(utils.AlignLeft, utils.Primary, "Button Primary", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var37), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var36), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var38 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var39 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									templ_7745c5c3_Err = components.ButtonOutlined(utils.AlignLeft, utils.Secondary, "Button Secondary", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var39), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var38), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var40 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var41 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									templ_7745c5c3_Err = components.ButtonOutlined(utils.AlignLeft, utils.Success, "Button Success", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var41), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var40), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var42 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var43 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									templ_7745c5c3_Err = components.ButtonOutlined(utils.AlignLeft, utils.Info, "Button Info", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var43), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var42), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var44 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var45 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									templ_7745c5c3_Err = components.ButtonOutlined(utils.AlignLeft, utils.Danger, "Button Danger", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var45), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var44), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Var46 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								templ_7745c5c3_Var47 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
									templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
									if !templ_7745c5c3_IsBuffer {
										templ_7745c5c3_Buffer = templ.GetBuffer()
										defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
									}
									templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									templ_7745c5c3_Err = components.ButtonOutlined(utils.AlignLeft, utils.Warning, "Button Warning", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
									if templ_7745c5c3_Err != nil {
										return errtrace.Wrap(templ_7745c5c3_Err)
									}
									if !templ_7745c5c3_IsBuffer {
										_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
									}
									return errtrace.Wrap(templ_7745c5c3_Err)
								})
								templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var47), templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var46), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							if !templ_7745c5c3_IsBuffer {
								_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
							}
							return errtrace.Wrap(templ_7745c5c3_Err)
						})
						templ_7745c5c3_Err = components.ColHalf(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var33), templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return errtrace.Wrap(templ_7745c5c3_Err)
						}
						if !templ_7745c5c3_IsBuffer {
							_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
						}
						return errtrace.Wrap(templ_7745c5c3_Err)
					})
					templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var17), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					templ_7745c5c3_Err = components.Spacer().Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					templ_7745c5c3_Var48 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
						if !templ_7745c5c3_IsBuffer {
							templ_7745c5c3_Buffer = templ.GetBuffer()
							defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
						}
						templ_7745c5c3_Var49 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
							templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
							if !templ_7745c5c3_IsBuffer {
								templ_7745c5c3_Buffer = templ.GetBuffer()
								defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
							}
							templ_7745c5c3_Var50 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Example of dashed coupon view.")
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.P().Render(templ.WithChildren(ctx, templ_7745c5c3_Var50), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Err = components.Coupon(components.CouponData{
								DiscountPercent: 20,
								Coupon:          "COUPONCODE",
							}).Render(ctx, templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							if !templ_7745c5c3_IsBuffer {
								_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
							}
							return errtrace.Wrap(templ_7745c5c3_Err)
						})
						templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var49), templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return errtrace.Wrap(templ_7745c5c3_Err)
						}
						if !templ_7745c5c3_IsBuffer {
							_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
						}
						return errtrace.Wrap(templ_7745c5c3_Err)
					})
					templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var48), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					templ_7745c5c3_Var51 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
						if !templ_7745c5c3_IsBuffer {
							templ_7745c5c3_Buffer = templ.GetBuffer()
							defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
						}
						templ_7745c5c3_Var52 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
							templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
							if !templ_7745c5c3_IsBuffer {
								templ_7745c5c3_Buffer = templ.GetBuffer()
								defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
							}
							templ_7745c5c3_Var53 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Example of coupon view with background.")
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.P().Render(templ.WithChildren(ctx, templ_7745c5c3_Var53), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							templ_7745c5c3_Err = components.Discount(components.DiscountData{
								Headline:      "This is a coupon headline",
								Discount:      "$30",
								ConditionText: "Valid until end of the month",
								CTA: components.CTA{
									Text: "Get your discount",
									Link: "https://example.com",
								},
							}).Render(ctx, templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							if !templ_7745c5c3_IsBuffer {
								_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
							}
							return errtrace.Wrap(templ_7745c5c3_Err)
						})
						templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var52), templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return errtrace.Wrap(templ_7745c5c3_Err)
						}
						if !templ_7745c5c3_IsBuffer {
							_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
						}
						return errtrace.Wrap(templ_7745c5c3_Err)
					})
					templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var51), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					templ_7745c5c3_Err = components.Divider().Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					templ_7745c5c3_Var54 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
						if !templ_7745c5c3_IsBuffer {
							templ_7745c5c3_Buffer = templ.GetBuffer()
							defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
						}
						templ_7745c5c3_Var55 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
							templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
							if !templ_7745c5c3_IsBuffer {
								templ_7745c5c3_Buffer = templ.GetBuffer()
								defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
							}
							templ_7745c5c3_Var56 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Id labore laboris non deserunt et ad eiusmod incididunt. Proident eiusmod ut esse id mollit aliqua. Voluptate Lorem in reprehenderit eu ea.")
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								templ_7745c5c3_Err = components.Link("", "http://soggy-stain.com?sfvsfa=234324&sfgsfs=srthstgserasdagarfwae.aefawefweGAEF.AEFAEWFWAEFGHTYJdgnsghbst35345&test=1").Render(ctx, templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.SecondaryText().Render(templ.WithChildren(ctx, templ_7745c5c3_Var56), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							if !templ_7745c5c3_IsBuffer {
								_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
							}
							return errtrace.Wrap(templ_7745c5c3_Err)
						})
						templ_7745c5c3_Err = components.ColFull(utils.AlignLeft).Render(templ.WithChildren(ctx, templ_7745c5c3_Var55), templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return errtrace.Wrap(templ_7745c5c3_Err)
						}
						if !templ_7745c5c3_IsBuffer {
							_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
						}
						return errtrace.Wrap(templ_7745c5c3_Err)
					})
					templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var54), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					if !templ_7745c5c3_IsBuffer {
						_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
					}
					return errtrace.Wrap(templ_7745c5c3_Err)
				})
				templ_7745c5c3_Err = components.Container(utils.BgWhite).Render(templ.WithChildren(ctx, templ_7745c5c3_Var5), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return errtrace.Wrap(templ_7745c5c3_Err)
				}
				if !templ_7745c5c3_IsBuffer {
					_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
				}
				return errtrace.Wrap(templ_7745c5c3_Err)
			})
			templ_7745c5c3_Err = components.Wrapper().Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" ")
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			templ_7745c5c3_Var57 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
				if !templ_7745c5c3_IsBuffer {
					templ_7745c5c3_Buffer = templ.GetBuffer()
					defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
				}
				templ_7745c5c3_Var58 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
					if !templ_7745c5c3_IsBuffer {
						templ_7745c5c3_Buffer = templ.GetBuffer()
						defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
					}
					templ_7745c5c3_Var59 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
						templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
						if !templ_7745c5c3_IsBuffer {
							templ_7745c5c3_Buffer = templ.GetBuffer()
							defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
						}
						templ_7745c5c3_Var60 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
							templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
							if !templ_7745c5c3_IsBuffer {
								templ_7745c5c3_Buffer = templ.GetBuffer()
								defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
							}
							templ_7745c5c3_Var61 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
								templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
								if !templ_7745c5c3_IsBuffer {
									templ_7745c5c3_Buffer = templ.GetBuffer()
									defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
								}
								_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("2024 ")
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								templ_7745c5c3_Err = components.Link("Company Name LLC", "https://example.com").Render(ctx, templ_7745c5c3_Buffer)
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" . All rights reserved.")
								if templ_7745c5c3_Err != nil {
									return errtrace.Wrap(templ_7745c5c3_Err)
								}
								if !templ_7745c5c3_IsBuffer {
									_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
								}
								return errtrace.Wrap(templ_7745c5c3_Err)
							})
							templ_7745c5c3_Err = components.SecondaryText().Render(templ.WithChildren(ctx, templ_7745c5c3_Var61), templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err != nil {
								return errtrace.Wrap(templ_7745c5c3_Err)
							}
							if !templ_7745c5c3_IsBuffer {
								_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
							}
							return errtrace.Wrap(templ_7745c5c3_Err)
						})
						templ_7745c5c3_Err = components.ColFull(utils.AlignCenter).Render(templ.WithChildren(ctx, templ_7745c5c3_Var60), templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err != nil {
							return errtrace.Wrap(templ_7745c5c3_Err)
						}
						if !templ_7745c5c3_IsBuffer {
							_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
						}
						return errtrace.Wrap(templ_7745c5c3_Err)
					})
					templ_7745c5c3_Err = components.Row().Render(templ.WithChildren(ctx, templ_7745c5c3_Var59), templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return errtrace.Wrap(templ_7745c5c3_Err)
					}
					if !templ_7745c5c3_IsBuffer {
						_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
					}
					return errtrace.Wrap(templ_7745c5c3_Err)
				})
				templ_7745c5c3_Err = components.Container(utils.Transparent).Render(templ.WithChildren(ctx, templ_7745c5c3_Var58), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return errtrace.Wrap(templ_7745c5c3_Err)
				}
				if !templ_7745c5c3_IsBuffer {
					_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
				}
				return errtrace.Wrap(templ_7745c5c3_Err)
			})
			templ_7745c5c3_Err = components.Wrapper().Render(templ.WithChildren(ctx, templ_7745c5c3_Var57), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return errtrace.Wrap(templ_7745c5c3_Err)
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return errtrace.Wrap(templ_7745c5c3_Err)
		})
		templ_7745c5c3_Err = components.Layout("en", "Components Preview", "Preview of all components").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return errtrace.Wrap(templ_7745c5c3_Err)
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return errtrace.Wrap(templ_7745c5c3_Err)
	})
}
